### ISSUE TITLE
Only health fot first partitions

### ISSUE THREAD

**Issue by bcnx** [narbehaj/zabbix-nvme#1]
Hi,

I only get Health data for the first NVMe partitions. Is this normal?

For instance: 
	
NVMe /dev/nvme0n1 Health

Thanks!

BC

**Comment by narbehaj** [comment]
Hi, 
Actually, it lists all the NVMe drives on the server and then gets the health status for each drive, not partition.
Do you see anything else which the script doesn't show?

**Comment by bcnx** [comment]
I might be actually confusing NVMe drive numbers and partitions. I both have:

/dev/nvme0
and
/dev/nvme0n1

It seems your template picks up the second name for a particular drive. I thus suspect everything works as expected, sorry for the noise,

BC

**Comment by narbehaj** [comment]
Yeah cool, no worries, as you can see in the script, it gets the whole device ID, doesn't matter how many partitions it has. Then it uses the `nvme`'s built-in command to check the health.

**Comment by bcnx** [comment]
Awesome, thanks for your time,

BC
